name: Tests 1

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if the repository is private
        run: exit 1
        if: ${{github.event.repository.private}}
      - name: Tests
        uses: rpill/test-project-action@main
        with:
          project: 's-chistogo-lista'
